name: Copy files with SCP

on:
  workflow_dispatch:  

jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files from Remote Server to /data
      uses: appleboy/scp-action@v0.1.1 
      with:
        host: ${{ secrets.DESTINATION_HOST }}
        port: 22
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source : "~/hemato/code/"
        target: "/data/"
        
    - name: Commit and Push Files to Repository
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add data/*
        git commit -m "Add files to /data folder"
        git push
